name: Brickproof Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Run Brickproof
      env: # Or as an environment variable
        TOKEN: ${{ secrets.TOKEN }}
        WORKSPACE_URL: ${{ secrets.WORKSPACE_URL }}

      run: |
        python3 brickproof version
        python3 brickproof edit-config -v repo.branch=$GITHUB_HEAD_REF
        cat ./brickproof.toml
        touch .bprc
        echo [default] >> .bprc
        echo workspace=$WORKSPACE_URL >> .bprc
        echo token=$TOKEN >> .bprc
        cat .bprc
        python3 brickproof run 
